### ISSUE TITLE
The close button of the color picker can't be reach by keyboard

### ISSUE THREAD

**Issue by decristm** [bfh/moodle-tiny_fontcolor#10]
If you navigate only with the keyboard, you can't reach the close button of the popup window of the color picker.
![image](https://github.com/bfh/moodle-tiny_fontcolor/assets/74793913/9bb6f19d-1a4e-480e-a5d1-355baada1338)
Yes, you can use the other button Cancel at the end, but then, you'll have to travel in all the input fields before. 
Thanks!

**Comment by srobotta** [comment]
This is an issue that I would like to drop. The reason is that with Ctrl + Tab you can navigate back in the form. Hitting Ctrl + Tab twice gets you to the cancel button. Furthermore hitting Escape closes the dialogue no matter which element has the focus at the moment.
