### ISSUE TITLE
Improve accessibility when you put a wrong hexa color code in Color picker

### ISSUE THREAD

**Issue by decristm** [bfh/moodle-tiny_fontcolor#11]
Hi!
When you put a wrong hexa code for the color, there's a popup window for the error message. This popup window is over an existing popup window, and it's not accessible. Then you click the OK button and the focus is not in the popup Color picker window on the hexa field (the field you need to correct), instead it's on the page under. So if you navigate with the keyboard or with a screen reader, it will be very difficult to use.
![image](https://github.com/bfh/moodle-tiny_fontcolor/assets/74793913/70f98f30-d6ca-4895-a141-42f8e51533f7)
Thanks!

**Comment by srobotta** [comment]
Hi,

Thank you for your 3 issues. I try to look at them as soon as possible but can promise any date yet. But I have noticed them when they came in and just would like to let you kow that I am aware of them.
I kindly as for a bit more patience.
Thank you.
