### ISSUE TITLE
HTML areas without files seem to fail with the tiny_fontcolor enabled

### ISSUE THREAD

**Issue by justinhunt** [bfh/moodle-tiny_fontcolor#16]
On Moodle 4.4.1+ (Build: 20240712) with version 20240627 of tiny_fontcolor TinyMCE fails to load under some circumstances. 

It was reported by a user of  one of my plugins (mod_minilesson) and I confirmed this also happens in the qtype_match answer options. It does not happen in description areas of activity modules. So where file support is enabled for some reason the problem is avoided.

The actual console error is:
first.js:4105 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).split is not a function
    at _exports.addQuickbarsToolbarItem (first.js:4105:3597)
    at _exports.configure (first.js:5366:664)
    at first.js:4095:6736
    at Array.forEach (<anonymous>)
    at getEditorConfiguration (first.js:4095:6670)
    at setupForTarget (first.js:4095:7808)

And it seems to ooccur because the value of quickbar in the following line of the following function is false.
_utils.addQuickbarsToolbarItem)(quickbar, "|", _common.forecolor),

define("tiny_fontcolor/configuration", ["exports", "editor_tiny/utils", "./common"], (function(_exports, _utils, _common) {
    Object.defineProperty(_exports, "__esModule", {
        value: !0
    }),
    _exports.configure = void 0;
    _exports.configure = instanceConfig=>{
        return {
            toolbar: (toolbar = instanceConfig.toolbar,
            toolbar = (0,
            _utils.addToolbarButtons)(toolbar, "formatting", [_common.forecolor, _common.backcolor])),
            menu: (menu = instanceConfig.menu,
            menu = (0,
            _utils.addMenubarItem)(menu, "format", _common.forecolor),
            menu = (0,
            _utils.addMenubarItem)(menu, "format", _common.backcolor)),
            quickbars_selection_toolbar: (quickbar = instanceConfig.quickbars_selection_toolbar,
            quickbar = (0,
            _utils.addQuickbarsToolbarItem)(quickbar, "|", _common.forecolor),
            quickbar = (0,
            _utils.addQuickbarsToolbarItem)(quickbar, "|", _common.backcolor))
        };
        var quickbar, menu, toolbar
    }
}

Everything else seems normal, this is the only 3rd party Tiny plugin installed. I was not able to reproduce it on my dev 4.4 site.

**Comment by srobotta** [comment]
Hi Justin,

I havend managed yet to check out the error in detail, but hopefully will do so in the comming weeks. Meanwhile, can you try to install the previous version (in github tagged with V0.5)? Hopefully the error should not show up there because there was a pull request for V0.6 that made the color icons appear in the context menu in the newest version.
However, as soon as I get there I will have a look and try to fix it.

Best regards, Stephan

**Comment by justinhunt** [comment]
Thanks. The client removed the plugin for now, but I will pass on the message and help them put it back in if they want to

**Comment by lucascherer** [comment]
I manage to make the plugin work by concatenating the value of quickbar with an empty string so the split function does not crash.

On the configuration.js file:

```
const configureQuickbarToolbar = (quickbar) => {
    quickbar = addQuickbarsToolbarItem(quickbar + '', '|', forecolor);
    quickbar = addQuickbarsToolbarItem(quickbar + '', '|', backcolor);
    return quickbar;
};
```

**Comment by srobotta** [comment]
Hi,

Today I was able to repoduce the error. I also think I have fixed the issue and therefore released version 0.7.

Best regards, Stephan

**Comment by pkgh** [comment]
Hi. Could be another patch is needed yet. After I upgraded to 0.7 of the plugin, the editor loads OK into Choice text fields, Feedback fields and Multiple tries fields for me, but after I highlight some text, I don't get the formatting popup (only the No autolink option, which I have activated):

![2024-08-22 , 18_01_54 - Editing a Multiple choice question _ pktest — Mozilla Firefox — tryb prywatny](https://github.com/user-attachments/assets/57cb838e-4897-4b7f-b17a-91ba3dd04202)


BTW - cf. https://tracker.moodle.org/browse/MDL-82672 .
Maybe the original problem has its roots in Tiny, and not in this plugin?

**Comment by pkgh** [comment]
PS. I can confirm that upgrading the plugin to version 0.7 fixes all those areas that previously failed to load the Tiny MCE editor on my Moodle 4.3.5+ . I list them on the Moodle tracker https://tracker.moodle.org/browse/MDL-82672 . They include:

- Descriptions of Files and URLs.
- "Overall feedback" fields in Quiz settings
- Feedback areas for answers in several question types: Simple calculated, Short answer, Multiple choice. (Interestingly, TinyMCE loaded OK into feedback areas for Calculated multichoice questions)
- Hint areas in Multiple tries sections of most questions types
- Combined feedback text areas in questions that support them (e.g. Multiple choice)
- Choices text when editing Multiple choice questions
- Question 1, 2 etc, text areas in Matching questions

However, in each of these fixed areas I see a deficient popup toolbar shown in my previous comment. 

What's also particularly interesting is that TinyMCE seems to fail to load also on sites where the Fontcolor plugin is not installed - such as on the Moodle sandbox sites (https://sandbox403.moodledemo.net/ , and the current 44 : ) . I've also hust now visited the QA site https://qa.moodledemo.net/my/courses.php , and here the problem does NOT occur.

**Comment by srobotta** [comment]
When investigating the error, I saw that there is no context menu where I wanted to add the color icons. This is what I have fixed so the Tiny is loading again. Also, It might be intented that in feedback and mulit answer options text formatting should be avoided. That would make sense IMHO. However, I have nevver checked in detail how the Tiny works (or better said is supposed to work) on these fields.

**Comment by pkgh** [comment]
Just spotted that the Moodle sandbox sites are from the latest STABLES :

Version 4.4.2 (Build: 20240812) 
Version 4.3.6 (Build: 20240812) 

rather than the latest weekly downloads, which are:

$release  = '4.3.6+ (Build: 20240821)'
$release  = '4.4.2+ (Build: 20240821)'

so I will try to upgrade my existing 43 and 44 test sites and see if the problem has perhaps disappeared there as well.

It will also be worth testing how version 0.7 of the plugin will act on those weeklies.

**Comment by pkgh** [comment]
Done some more tests on the very latest Moodle versions published on 23 August. 
Report here: 
https://tracker.moodle.org/browse/MDL-82672?focusedId=1105453&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1105453 .

The fontcolor plugin behaved OK in my tests and would load into the popup toolbar even though the basic icons would often not, as pointed out in my report. I expect the Moodle devs to fix the Moodle core code for all the three supported versions of Moodle. Remains to be seen, and whether any later changes affect the fontcolor plugin.

HTH.
