### ISSUE TITLE
TinyMCE fails when creating a qtype_multichoice question

### ISSUE THREAD

**Issue by ndunand** [bfh/moodle-tiny_fontcolor#17]
Hi @srobotta and @lucaboesch ,

Thanks for this useful plugin! We have just – I hope reproducibly – found out that enabling the plugin prevents Tiny from instantiating when creating or editing a Multichoice question.

When creating/editing the question, about 18 editors are spawned (!) but only the first two succeed. The other 16 fail with the same error, which seems to be related to the implementation of the quicktoolbar feature from your plugin – implemented in b031884e6125e1 .

Deactivating your plugin solves the issue.

We have this issue with release 0.6 but not with release 0.5.

**Comment by srobotta** [comment]
Hi @ndunand,

I am not sure where the error comes from. Issue #16 deals with the same issue but I was unable to reproduce the issue, both yours and the other one. However, I did some change in the plugin and pushed that to main. Could you please check whether that fixes the problem?
Thank you in advance.

**Comment by ndunand** [comment]
Hi @srobotta ,

Thanks for the update. It does not seem to fix the issue however. And indeed is seems related (or the same as) #16 as indeed the `quickbar` variable resolved to `false` in this case too, raising an error.

**Comment by ndunand** [comment]
Hi @srobotta ,
Good news! Indeed that seems to solve the issue on our end too.
Cheers,
Nicolas

**Comment by pkgh** [comment]
Added a comment under #16 , which could be relevant?

https://github.com/bfh/moodle-tiny_fontcolor/issues/16#issuecomment-2305148586
